name: Continuous Integration
on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
          python-version: '3.8'

    - name: Show Python version
      run: python -v
        

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: jenk

    - name: Show directory
      run: 'pwd'

    - name: List files
      run: 'ls -al'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      uses: onichandame/python-test-action@master

    - name: Run tests
      run: echo "Tests to be added"
